### ISSUE TITLE
yii\grid\CheckboxColumn filter row selected.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [mickgeek/yii2-actionbar#2]
Hi, extencion excellent, I would like to filter the gridview by yii\grid\CheckboxColumn rows selected this is possible with your extension, that form could be done and thank you very much in advance for your answer,

Thks,

Wilmer.

**Comment by mickgeek** [comment]
Hi!

The catch is that the extension sends a POST request and query parameters are not displayed. If it you are not confused, add the filtering option in the widget:
```php
'bulkActionsItems' => [
    'General' => [
        'general-filter' => 'Filter',
    ],
],
'bulkActionsOptions' => [
    'options' => [
        'general-filter' => [
            'url' => \yii\helpers\Url::to(),
        ],
    ],
],
```

In the action, add the similar code (before the declaration of the `$searchModel`):
```php
$ids = Yii::$app->request->post('ids');
if ($ids) {
    Yii::$app->request->setQueryParams([
        'ModelSearch' => ['id' => implode(', ', $ids)],
    ]);
}

$searchModel = new ModelSearch();
$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
```

And in the `ModelSearch` class, add the filter (after load the seach form data and validate):
```php
if (!($this->load($params) && $this->validate())) {
    return $dataProvider;
}
        
if ($this->id) {
    $ids = explode(',', $this->id);
    $query->andFilterWhere(['id' => $ids]);
}
```

**Comment by tecnologiaterabyte** [comment]
thanks for replying, works perfectly, as would be done to use a button instead of the menu.

View (index.php):

    <?= ActionBar::widget([
        'grid' => 'kv-grid',
        'templates' => [
            '{bulk-actions}' => ['class' => 'col-xs-4'],
            '{filter}' => ['class' => 'col-xs-8 text-right'],
        ],
        'bulkActionsItems' => [
            'General' => [
                'general-filter' => 'Filter Rows Select',
            ],
        ],
        'bulkActionsOptions' => [
            'options' => [
                'general-filter' => [
                    'url' => \yii\helpers\Url::to(),
                ],
            ],
        ],
        'elements' => [
            'filter' => Html::a(
                '<i class="glyphicon glyphicon-download-alt"></i><span>&nbsp;&nbsp; Filter Rows Select</span>',
                [url::to('/horarios/index')],
                ['class' => 'btn btn-success']
            ),
        ],
    ]) ?>

![gridview_filter](https://cloud.githubusercontent.com/assets/4957021/5970886/5663ce14-a80c-11e4-9ff0-0a2aa2eacc3c.jpg)

**Comment by mickgeek** [comment]
In this case, the best option is to send the GET request. Your action must be standard, but the `ModelSearch` class should look like that in my previous post.

Add the button in the widget:
```php
'elements' => [
    'filter-checked' => Html::a(
        '<span class="glyphicon glyphicon-filter"></span> Filter Checked',
        \yii\helpers\Url::current(['ModelSearch' => ['id' => '']]),
        ['id' => 'filter-checked-btn', 'class' => 'btn btn-default']
    ),
],
```

Then we need a special class of checkbox rows. Edit the `CheckboxColumn` options as follow:
```php
'columns' => [
    [
        'class' => '\yii\grid\CheckboxColumn',
        'checkboxOptions' => ['class' => 'checkbox-row'],
    ],
],
```

It remains to register the JS code in the view (note the comments):
```php
<?php $this->registerJs("$('.select-on-check-all, .checkbox-row').change(function() {
    setTimeout(function() {
        var ids = $('#your-grid').yiiGridView('getSelectedRows'), // change the grid id
            queryParams = {},
            queryString = location.search.substring(1),
            regexp = /([^&=]+)=([^&]*)/g, m;

        while (matches = regexp.exec(queryString)) {
            queryParams[decodeURIComponent(matches[1])] = decodeURIComponent(matches[2]);
        }

        queryParams['ModelSearch[id]'] = ids.join(', '); // change the model name
        $('#filter-checked-btn').attr('href', location.pathname + '?' + $.param(queryParams));
    }, 10);
});"); ?>
```

Also this solution can work without the extension, just add a filter button to any place.

**Comment by tecnologiaterabyte** [comment]
Thank you for your help, excellent your help with js were clarified all my doubts, besides this serve me for many other things, thanks for sharing your knowledge.

Thks,

Wilmer.

**Comment by tecnologiaterabyte** [comment]
Sorry for the inconvenience again, if I want to use this code with pjax it works before applying the filter, and then I apply it stops working, and it disappears because the js code of gridview, there will be some way to fix this, believe me before you ask again I searched and read but I could not solve it.

Greetings and real apology.

Before Filter: (js code register here)

![error_pjax_01](https://cloud.githubusercontent.com/assets/4957021/5992592/1daf7828-aa02-11e4-8b74-8b65300d7fc4.jpg)

After filter: (disappears js code not found)

![error_pjax_02](https://cloud.githubusercontent.com/assets/4957021/5992595/4f863788-aa02-11e4-8d8a-fa634a4065c9.jpg)

**Comment by mickgeek** [comment]
I think you need to enclose all the content between Pjax `begin()` and `end()` calls, like this:
```php
<?php Pjax::begin(); ?>
    // button
    // gridview
    // js
<?php Pjax::end(); ?>
```

**Comment by tecnologiaterabyte** [comment]
Thks @mickgeek.

**Comment by mickgeek** [comment]
You're welcome :ok_hand:
