### ISSUE TITLE
Составной ключ в колонке чекбоксов

### ISSUE THREAD

**Issue by G1K** [mickgeek/yii2-actionbar#8]
https://github.com/mickgeek/yii2-actionbar/blob/028f38229bfee69ced4748f2cb869c5d4a630436/Widget.php#L236
В случае если ключ составной при формировании виртуальной формы получаем вот такое https://w6p.ru/NDMwYW.png

В ядре в value CheckboxColumn пишется Json, но при получении выделенных строк выдается массив из объектов. Нужно обратно делать JSON_ENCODE
https://github.com/yiisoft/yii2/blob/20aa5080189cbacd4180d3b115752817921eb364/framework/grid/CheckboxColumn.php#L123

**Comment by mickgeek** [comment]
:+1: 

Сделаешь пулл-реквест?

**Comment by mickgeek** [comment]
Готово: https://github.com/mickgeek/yii2-actionbar/commit/924ada569f2f05a3020022df129960e42730fbf3. Благодарю.

Хочу также заметить, что при создании составного ключа необходимо использовать integer-поля.
